[variables]
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_LOGLEVEL = "verbose"

[phases.setup]
nixPkgs = ["nodejs_20.19", "jq", "caddy"]

[phases.caddy]
dependsOn = ["setup"]
nixpkgsArchive = "nixos-unstable"

[phases.build]
dependsOn = ["setup"]
cmds = [
  # Verifikasi versi Node.js
  "node --version",
  # Bersihkan cache npm
  "npm cache clean --force",
  # Hapus folder node_modules (gunakan `|| true` untuk menghindari error jika folder tidak ada)
  "rm -rf node_modules || true",
  # Instal dependensi dengan opsi fleksibel
  "npm install --no-audit --no-fund --legacy-peer-deps || npm install --no-audit --no-fund --force",
  # Build aplikasi Angular
  "npm run build"
]

[phases.fmt]
dependsOn = ["caddy", "build"]
cmds = ["caddy fmt --overwrite Caddyfile"]

[start]
cmd = "export ANGULAR_OUTPUT_PATH=$(jq -r '[.projects[] | .architect.build.options.outputPath][0]' angular.json) && exec caddy run --config Caddyfile --adapter caddyfile 2>&1"