[variables]
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"

[phases.setup]
# Gunakan nodejs_20 untuk mendapatkan versi 20.x yang kompatibel dengan Angular CLI
nixPkgs = ["nodejs_20", "jq", "caddy"]

[phases.caddy]
dependsOn = ["setup"]
# Gunakan commit yang diketahui memiliki nodejs_20
nixpkgsArchive = "5bf1cadb72fd5cf8648a373bad50d691c6c91ec3" # Nixpkgs unstable (Mei 2024)

[phases.build]
dependsOn = ["setup"]
cmds = [
  # Verifikasi versi Node.js
  "node --version",
  # Install dependensi
  "npm ci",
  # Build aplikasi Angular
  "npm run build"
]

[phases.fmt]
dependsOn = ["caddy", "build"]
cmds = ["caddy fmt --overwrite Caddyfile"]

[start]
cmd = "export ANGULAR_OUTPUT_PATH=$(jq -r '[.projects[] | .architect.build.options.outputPath][0]' angular.json) && exec caddy run --config Caddyfile --adapter caddyfile 2>&1"