[variables]
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"

[phases.setup]
# Gunakan nodejs tanpa versi spesifik, atau nodejs-20 (tanpa _x) jika tersedia
nixPkgs = ["nodejs", "jq", "caddy"]

[phases.caddy]
dependsOn = ["setup"]
# Gunakan commit yang lebih baru yang diketahui memiliki node.js 20
nixpkgsArchive = "5bf1cadb72fd5cf8648a373bad50d691c6c91ec3" # Nixpkgs unstable (7 Mei 2024)

[phases.fmt]
dependsOn = ["caddy"]
cmds = ["caddy fmt --overwrite Caddyfile"]

[start]
# Gunakan nodejs tanpa versi spesifik
cmd = "export ANGULAR_OUTPUT_PATH=$(jq -r '[.projects[] | .architect.build.options.outputPath][0]' angular.json) && export PATH=$(nix eval --raw nixpkgs#nodejs)/bin:$PATH && exec caddy run --config Caddyfile --adapter caddyfile 2>&1"